apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgresql
 namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
     app: postgresql
 template:
   metadata:
     labels:
       app: postgresql
   spec:
     containers:
       - name: postgresql
         image: postgres:13
         env:
           - name: POSTGRES_USER
             value: sonar
           - name: POSTGRES_PASSWORD
             value: sonar
           - name: POSTGRES_DB
             value: sonarqube
         ports:
           - containerPort: 5432