apiVersion: v1
kind: Pod
metadata:
 name: jenkins-agent
spec:
 containers:
   - name: jnlp
     image: jenkins/inbound-agent:latest
     args: ["$(JENKINS_SECRET)", "$(JENKINS_NAME)"]
   - name: dind
     image: docker:dind
     securityContext:
       privileged: true
     env:
       - name: DOCKER_TLS_CERTDIR
         value: ""
     volumeMounts:
       - name: dind-storage
         mountPath: /var/lib/docker
 volumes:
   - name: dind-storage
     emptyDir: {}