apiVersion: apps/v1
kind: Deployment
metadata:
 name: sonarqube
 namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
     app: sonarqube
 template:
   metadata:
     labels:
       app: sonarqube
   spec:
     containers:
       - name: sonarqube
         image: sonarqube:lts-community  # Official Docker image
         ports:
           - containerPort: 9000
         env:
           - name: SONAR_JDBC_URL
             value: "jdbc:postgresql://postgresql:5432/sonarqube"
           - name: SONAR_JDBC_USERNAME
             value: "sonar"
           - name: SONAR_JDBC_PASSWORD
             value: "sonar"
         volumeMounts:
           - mountPath: /opt/sonarqube/data
             name: sonarqube-data
           - mountPath: /opt/sonarqube/logs
             name: sonarqube-logs
     volumes:
       - name: sonarqube-data
         emptyDir: {}
       - name: sonarqube-logs
         emptyDir: {}