environment:
 name: local_k8s_env_helm
 identifier: local_k8s_env_helm
 orgIdentifier: default
 projectIdentifier: Poc_project
 type: PreProduction
 infrastructureDefinitions:
   - identifier: local_k8s_infra_helm
     type: KubernetesDirect
     spec:
       connectorRef: k8s_connector
       namespace: default
       releaseName: spring-boot-app-helm