apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:

      containers:
      - name: jenkins
        image: anunarayan/myjenkins-docker
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: CHROME_BIN
          value: "/usr/bin/google-chrome"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: google-chrome-bin
          mountPath: /usr/bin/google-chrome
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: google-chrome-bin
        hostPath:
          path: /usr/bin/google-chrome
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30081
  - name: agent
    port: 50000
    targetPort: 50000
    nodePort: 30050
  selector:
    app: jenkins
